#!/bin/sh
 
DIFF=/usr/bin/diff
ECHO=/bin/echo
 
$ECHO -n "Checking sspatt: "

../src/sspatt hiv.fasta -l 4 -m 1 --all-words > test_result_sspatt && \
$DIFF test_result_sspatt result_sspatt 

if test $? = 0 ; then $ECHO "ok." ; else $ECHO "NOT ok!" ; exit -1; fi
