#!/bin/sh
 
DIFF=/usr/bin/diff
ECHO=/bin/echo
 
$ECHO -n "Checking xspatt: "

../src/xspatt hiv.fasta  -m 0 -p atatag -p aaacaaa > test_result_xspatt && \
$DIFF test_result_xspatt result_xspatt 

if test $? = 0 ; then $ECHO "ok." ; else $ECHO "NOT ok!" ; exit -1; fi
