#!/bin/sh
 
DIFF=/usr/bin/diff
ECHO=/bin/echo
 
$ECHO -n "Checking gspatt: "

../src/gspatt hiv.fasta -l 4 -m 0 --all-words > test_result_gspatt && \
$DIFF test_result_gspatt result_gspatt 

if test $? = 0 ; then $ECHO "ok." ; else $ECHO "NOT ok!" ; exit -1; fi
