#!/bin/sh
 
DIFF=/usr/bin/diff
ECHO=/bin/echo
 
$ECHO -n "Checking cpspatt: "

../src/cpspatt hiv.fasta -l 4 -m 0 --all-words > test_result_cpspatt && \
$DIFF test_result_cpspatt result_cpspatt 

if test $? = 0 ; then $ECHO "ok." ; else $ECHO "NOT ok!" ; exit -1; fi
